/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author admin
 */
public class Bai3 extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Bai3.class.getName());

    /**
     * Creates new form Bai3
     */
    public Bai3() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        nutCong = new javax.swing.JButton();
        nutTru = new javax.swing.JButton();
        nutNhan = new javax.swing.JButton();
        nutChia = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        khungA = new javax.swing.JTextField();
        ketQua = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        khungB = new javax.swing.JTextField();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("A:");

        jLabel2.setText("B:");

        nutCong.setText("+");
        nutCong.addActionListener(this::nutCongActionPerformed);

        nutTru.setText("-");
        nutTru.addActionListener(this::nutTruActionPerformed);

        nutNhan.setText("*");
        nutNhan.addActionListener(this::nutNhanActionPerformed);

        nutChia.setText("/");
        nutChia.addActionListener(this::nutChiaActionPerformed);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Máy tính đơn giản");

        jLabel4.setText("Kết quả:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(128, 128, 128)
                .addComponent(jLabel3)
                .addContainerGap(156, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(khungA, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(nutCong))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(khungB, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(nutTru)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nutNhan)
                            .addComponent(nutChia))
                        .addGap(31, 31, 31))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ketQua, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel3)
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(nutCong)
                    .addComponent(nutNhan)
                    .addComponent(khungA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(nutTru)
                    .addComponent(nutChia)
                    .addComponent(khungB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(ketQua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(144, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nutCongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nutCongActionPerformed
        try {
        double a = Double.parseDouble(khungA.getText());
        double b = Double.parseDouble(khungB.getText());
        ketQua.setText(String.valueOf(a + b));
    } catch (NumberFormatException e) {
        javax.swing.JOptionPane.showMessageDialog(this, "Vui lòng nhập số hợp lệ!");
    }
    }//GEN-LAST:event_nutCongActionPerformed

    private void nutNhanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nutNhanActionPerformed
        try {
        double a = Double.parseDouble(khungA.getText());
        double b = Double.parseDouble(khungB.getText());
        ketQua.setText(String.valueOf(a * b));
    } catch (NumberFormatException e) {
        javax.swing.JOptionPane.showMessageDialog(this, "Vui lòng nhập số hợp lệ!");
    }
    }//GEN-LAST:event_nutNhanActionPerformed

    private void nutTruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nutTruActionPerformed
        try {
        double a = Double.parseDouble(khungA.getText());
        double b = Double.parseDouble(khungB.getText());
        ketQua.setText(String.valueOf(a - b));
    } catch (NumberFormatException e) {
        javax.swing.JOptionPane.showMessageDialog(this, "Vui lòng nhập số hợp lệ!");
    }
    }//GEN-LAST:event_nutTruActionPerformed

    private void nutChiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nutChiaActionPerformed
        try {
        double a = Double.parseDouble(khungA.getText());
        double b = Double.parseDouble(khungB.getText());
        if (b == 0) {
            javax.swing.JOptionPane.showMessageDialog(this, "Không thể chia cho 0!");
        } else {
            ketQua.setText(String.valueOf(a / b));
        }
    } catch (NumberFormatException e) {
        javax.swing.JOptionPane.showMessageDialog(this, "Vui lòng nhập số hợp lệ!");}
    }//GEN-LAST:event_nutChiaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Bai3().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField ketQua;
    private javax.swing.JTextField khungA;
    private javax.swing.JTextField khungB;
    private javax.swing.JButton nutChia;
    private javax.swing.JButton nutCong;
    private javax.swing.JButton nutNhan;
    private javax.swing.JButton nutTru;
    // End of variables declaration//GEN-END:variables
}
