/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author admin
 */
public class khungChinh extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(khungChinh.class.getName());

    /**
     * Creates new form khungChinh
     */
    public khungChinh() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nut1 = new javax.swing.JButton();
        nut3 = new javax.swing.JButton();
        nut4 = new javax.swing.JButton();
        nut5 = new javax.swing.JButton();
        nut2 = new javax.swing.JButton();
        nut6 = new javax.swing.JButton();
        nut7 = new javax.swing.JButton();
        nut8 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        nut1.setText("Bài 1");
        nut1.addActionListener(this::nut1ActionPerformed);

        nut3.setText("Bài 3");
        nut3.addActionListener(this::nut3ActionPerformed);

        nut4.setText("Bài 4");
        nut4.addActionListener(this::nut4ActionPerformed);

        nut5.setText("Bài 5");
        nut5.addActionListener(this::nut5ActionPerformed);

        nut2.setText("Bài 2");
        nut2.addActionListener(this::nut2ActionPerformed);

        nut6.setText("Bài 6");
        nut6.addActionListener(this::nut6ActionPerformed);

        nut7.setText("Bài 7");
        nut7.addActionListener(this::nut7ActionPerformed);

        nut8.setText("Bài 8");
        nut8.addActionListener(this::nut8ActionPerformed);

        jLabel1.setText("Nhóm 1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(nut4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(nut8))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(nut3)
                        .addGap(115, 115, 115)
                        .addComponent(nut7))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(nut1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(nut5))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(nut2)
                        .addGap(115, 115, 115)
                        .addComponent(nut6)))
                .addGap(73, 73, 73))
            .addGroup(layout.createSequentialGroup()
                .addGap(170, 170, 170)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nut1)
                    .addComponent(nut5))
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nut6)
                    .addComponent(nut2))
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nut3)
                    .addComponent(nut7))
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nut4)
                    .addComponent(nut8))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nut1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nut1ActionPerformed
        Bai1 b = new Bai1();
        b.setVisible(true);
        b.setLocationRelativeTo(null);
    }//GEN-LAST:event_nut1ActionPerformed

    private void nut3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nut3ActionPerformed
        Bai3 b = new Bai3();
        b.setVisible(true);
        b.setLocationRelativeTo(null);
    }//GEN-LAST:event_nut3ActionPerformed

    private void nut4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nut4ActionPerformed
        Bai4 b = new Bai4();
        b.setVisible(true);
        b.setLocationRelativeTo(null);
    }//GEN-LAST:event_nut4ActionPerformed

    private void nut5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nut5ActionPerformed
        Bai5 b = new Bai5();
        b.setVisible(true);
        b.setLocationRelativeTo(null);
    }//GEN-LAST:event_nut5ActionPerformed

    private void nut2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nut2ActionPerformed
        Bai2 b = new Bai2();
        b.setVisible(true);
        b.setLocationRelativeTo(null);
    }//GEN-LAST:event_nut2ActionPerformed

    private void nut6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nut6ActionPerformed
        Bai6 b = new Bai6();
        b.setVisible(true);
        b.setLocationRelativeTo(null);
    }//GEN-LAST:event_nut6ActionPerformed

    private void nut7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nut7ActionPerformed
       Bai7 b = new Bai7();
        b.setVisible(true);
        b.setLocationRelativeTo(null);
    }//GEN-LAST:event_nut7ActionPerformed

    private void nut8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nut8ActionPerformed
        Bai8 b = new Bai8();
        b.setVisible(true);
        b.setLocationRelativeTo(null);
    }//GEN-LAST:event_nut8ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new khungChinh().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton nut1;
    private javax.swing.JButton nut2;
    private javax.swing.JButton nut3;
    private javax.swing.JButton nut4;
    private javax.swing.JButton nut5;
    private javax.swing.JButton nut6;
    private javax.swing.JButton nut7;
    private javax.swing.JButton nut8;
    // End of variables declaration//GEN-END:variables
}
